[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
exclude = '''
	(
		src/rtctools/_version.py
	)
'''

[tool.ruff]
lint.ignore = [
	"B904", # Fix someday: raising exceptions within except
	"B905", # zip() without explicit strict parameter - not available in Python 3.9
]
line-length = 100
lint.select = [
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "E", # default / pycodestyle
    "F", # default / pyflakes
    "I", # isort
    "W", # pycodestyle

]
